apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-coordinator-deployment
  labels:
    app: druid-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-coordinator
  template:
    metadata:
      labels:
        app: druid-coordinator
    spec:
      containers:
        - name: druid-coordinator
          image: apache/druid:0.23.0
          args:
            - coordinator
          volumeMounts:
            - mountPath: /opt/shared
              name: druid-shared
            - mountPath: /opt/druid/var
              name: coordinator-var
          ports:
            - containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          envFrom:
            - configMapRef:
                name: 'druid-config'
      volumes:
        - name: coordinator-var
          hostPath:
            path: /private/tmp/data/coordinator_var
            type: Directory
        - name: druid-shared
          hostPath:
            path: /private/tmp/data/druid_shared
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  selector:
    app: druid-coordinator
  ports:
    - protocol: TCP
      name: druid-coordinator-port
      port: 8081
      targetPort: 8081