apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-router-deployment
  labels:
    app: druid-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-router
  template:
    metadata:
      labels:
        app: druid-router
    spec:
      containers:
        - name: druid-router
          image: apache/druid:0.23.0
          args:
            - router
          volumeMounts:
            - mountPath: /opt/druid/var
              name: router-var
          ports:
            - containerPort: 8888
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          envFrom:
            - configMapRef:
                name: 'druid-config'
      volumes:
        - name: router-var
          hostPath:
            path: /private/tmp/data/router_var
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  type: NodePort
  selector:
    app: druid-router
  ports:
    - protocol: TCP
      name: druid-router-port
      port: 8888
      targetPort: 8888
      nodePort: 30101