apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: global-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
        type: local
      