apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
          image: yravinderkumar33/livy
          volumeMounts:
            - mountPath: /opt/spark-data
              name: source-data
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 4040
            - containerPort: 8998
          env:
            - name: SPARK_MODE
              value: master  
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: KAFKA_URL 
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: KAFKA_TOPIC_NAME 
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: SPARK_RPC_AUTHENTICATION_ENABLED
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: SPARK_RPC_ENCRYPTION_ENABLED
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
            - name: SPARK_SSL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: SPARK_SSL_ENABLED
      volumes:
        - name: source-data
          hostPath:
          # mounting the path to all the source files for the spark job
            path: /Users/ravinderkumar/workspace/sanketika/assignment/Data-pipeline/assets/telemetry
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - protocol: TCP
      name: spark-ui-port
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: spark-ui-port-2
      port: 4040
      targetPort: 4040
    - protocol: TCP
      name: spark-master-port
      port: 7077
      targetPort: 7077
    - protocol: TCP
      name: livy-port
      port: 8998
      targetPort: 8998
      nodePort: 30190