apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 30182
    targetPort: 9092
  selector:
    app: kafka-broker